# RegionForcefield Configuration

# Enable debug logging (useful for troubleshooting)
debug: false

# How often to update forcefields (in ticks, 20 ticks = 1 second)
update-interval-ticks: 20

# Maximum distance (in blocks) at which forcefields will be rendered
# Reducing this can improve performance on servers with many regions
max-render-distance: 100

# Distance between particles (in blocks)
# Smaller values = more particles = more detailed forcefields but more performance intensive
particle-spacing: 0.5

# Whether to render the walls (faces) of regions, or just the edges
# Setting to false will only render the outlines/edges
render-walls: true

# Particle color (RGB values from 0-255)
particle-color:
  red: 147
  green: 112
  blue: 219

# Particle size (recommended range: 0.5 to 2.0)
particle-size: 1.0

# Block rendering settings
# Whether to render actual blocks (glass panes) in addition to particles
render-blocks: true

# Distance between blocks (in blocks)
# Higher values = fewer blocks = better performance
# Must be >= particle-spacing
block-spacing: 1.0

# Block material to use for forcefields
# Examples: PURPLE_STAINED_GLASS_PANE, BARRIER, GLASS, LIGHT_BLUE_STAINED_GLASS
# See https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html for all options
block-material: PURPLE_STAINED_GLASS_PANE
