name: RegionForcefield
version: ${version}
main: loganintech.regionforcefield.RegionForcefieldPlugin
api-version: '1.21'
depend: [WorldGuard]
author: loganintech
description: Renders visible forcefields around WorldGuard regions that players cannot enter
website: https://github.com/loganintech

commands:
  forcefield:
    description: Manage RegionForcefield plugin
    usage: /<command> [debug|reload|status|info|help]
    aliases: [ff, regionforcefield]
    permission: regionforcefield.command

permissions:
  regionforcefield.*:
    description: Grants all RegionForcefield permissions
    default: op
    children:
      regionforcefield.command: true
      regionforcefield.debug: true
      regionforcefield.reload: true
      regionforcefield.status: true
      regionforcefield.info: true
      regionforcefield.material: true
      regionforcefield.help: true
  regionforcefield.command:
    description: Allows access to the base /forcefield command
    default: true
  regionforcefield.debug:
    description: Allows toggling debug mode and using test command
    default: op
  regionforcefield.reload:
    description: Allows reloading the plugin configuration
    default: op
  regionforcefield.status:
    description: Allows viewing plugin status
    default: op
  regionforcefield.info:
    description: Allows viewing region information
    default: true
  regionforcefield.material:
    description: Allows changing the forcefield block material
    default: op
  regionforcefield.help:
    description: Allows viewing command help
    default: true
